apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-4
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-apps-4
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: my-apps/app-4
    repoURL: https://github.com/reccaneo/argocd-app-of-apps.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true